export enum Configuration {
    APP_NAME = 'APP_NAME',
    APP_MAIL = 'APP_MAIL',
    PORT = 'PORT',
    DATABASE_URI = 'DATABASE_URI',
    TOKEN_SECRET = 'TOKEN_SECRET',
    AWS_S3_BUCKET = 'AWS_S3_BUCKET',
    AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
    AWS_ACCESS_SECRET_KEY = 'AWS_ACCESS_SECRET_KEY',
    SMTP_TRANSPORT = 'SMTP_TRANSPORT',
}